### ISSUE TITLE
Q: cluster size

### ISSUE THREAD

**Issue by ivanjaros** [prologic/bitraft#30]
I need to sync configuration among 50-100 servers around the globe where one use case is that only one server can write, the rest can only read. The other use case is that each server can write but never the same keys. There are no clients, this is purely for managing configuration. Is Bitraft suitable for this? I was looking at etcd but they say 5 nodes is the ideal number but that is just not enough for what I need, is Bitraft better in this aspect?

I also need/want to be able to react on certain changes locally, instead fo running a query in a loop, does Bitraft support watching keys or something like that?

**Comment by prologic** [comment]
Yes I agree, that GHA workflow is kind of rubbish. I'll remove it! Thanks for 👎 'ing it! 🤗

Now to answer your questions... Unfortunately I have only bad news for you, No Bitraft is not suitable for _any_ of what you currently described. I wouldn't even touch it with a 10ft pole to be honest. And here is why:

- It was built as a Toy on top of the very stable, highly performant key/value store [prologic/bitcask](https://github.com/prologic/bitcask) which is sorta/kinda (_but not really_) like BoltDB, RocksDB, etc.
- It uses a transport layer for consensus choose author is unfortunately a bit slow at upgrading his library and keeping up with the latest Hashicorp Raft changes.
- Since Bitraft is basically Bitcask + Raft, it therefore requires the same kind of setup as ETCD. 3 nodes or 5 nodes ideally.

However... All that being said, I don't want to discourage you from your efforts. Bitraft _could_ be adapted to do what you want, but it might take some effort on your part and/or maybe mine too!

I just haven't found the time/effort/energy to date to really turn Bitraft into an actual distributed key/value store that I would consider "Production" grade/ready -- Bitcask OTOH **is**.

So where does this left you and your quest? Interested in collaborating on something? The benefit of utilising Bitcask here is that Bitcask is high performance and reliable with some very nice guarantees.

**Comment by prologic** [comment]
I also recognise you as the same person that [made this comment](https://github.com/genjidb/genji/issues/31#issuecomment-690100134) 😀 I would really love to work with you on this and figure out what you found wrt to [prologic/bitcask](https://github.com/prologic/bitcaks) 🙇‍♂️

**Comment by ivanjaros** [comment]
ok, thanks for the info. seems anything that usew raft is a no go.

**Comment by prologic** [comment]
> sorry, i use bolt and badger and i have no reason to spend my time on other stuff that i have no use for.

But you clearly did. You _spent_ time on constructing some benchmarks and comparisons between Bolt/Badger/Bitcask and as such your comment I linked to is unfair if you are not willing to back that up with some data and share your findings. I appreciate that you don't have "time", but if you are not willing to share your findings, It would be nice if you retracted your statement as it would then be unfounded.
